### ISSUE TITLE
Add All to Cart From wishlist button not working

### ISSUE THREAD

**Issue by adarsh-ceymox** [magepow/magento-2-ajax-cart#1]
**Add All to Cart** From wishlist button not working with more than 1 product in wishlist. Getting this error
_We can't add this item to your shopping cart right now._

![image](https://user-images.githubusercontent.com/73999443/113145468-10165180-924c-11eb-9681-01fcfabf9b6d.png)

I am using  Magento ver. 2.4.1

**Comment by magiccart** [comment]
Hi, If the list products have a product have options Magento will notify this error. This is an error in default Magento, not our module. You can try to disable Ajaxcart module and check on default Magento still get the same result.
