### ISSUE TITLE
Problem to add new product in cart when have sold out product in cart

### ISSUE THREAD

**Issue by acm-junior** [magepow/magento-2-ajax-cart#4]
Hi, 
We have a little bug when use the extension...
For example when a "customer A" is making a purchase and normally adding simple products to the cart, and other peaple "customer B" at the same time finalizes an order that contains  for the same product that only had one in stock, that same product is sold out and dont have more in stock. But if "customer A" who have this product in your cart, try to add some other product through the category page, the loading to add is in a loop and does not add or appear an error message, only the loading image of adding the product forever... its because have one product in her shopping cart we dont have more in stock... they need to refresh the page, go to the shopping card and delete this product, but dont apear this warning if they buy normaly in category pages and the product they have in cart is sold out in that moment, and they try to add another product and ocour this error/looping apear the image to waiting to add the new product but not end, stay a loop... could you help us please.. .  sorry for my english :)
thanks.

**Comment by ngoducnhuiit** [comment]
Thank you for notifying us of this error. We have updated the bug. Best regards .
